I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 20, in script
    show kapti namaste(Custom)
Exception: Image 'kapti namaste' does not accept attributes '(Custom)'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 20, in script
    show kapti namaste(Custom)
  File "D:\renpy-8.3.3-sdk\renpy\ast.py", line 1111, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\renpy-8.3.3-sdk\renpy\ast.py", line 1074, in show_imspec
    renpy.config.show(name,
  File "D:\renpy-8.3.3-sdk\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "D:\renpy-8.3.3-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "D:\renpy-8.3.3-sdk\renpy\display\displayable.py", line 249, in _duplicate
    args.extraneous()
  File "D:\renpy-8.3.3-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'kapti namaste' does not accept attributes '(Custom)'.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.3.24111502
A Gold Story 1.0
Sun Dec 15 19:30:59 2024
